

spring.datasource.url=jdbc:postgresql://task-manager-project-ginseku.postgres.database.azure.com:5432/postgres?sslmode=require
spring.datasource.username=${AZURESQL_USERNAME}
spring.datasource.password=${AZURESQL_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# ===============================
# Admin Settings
# ===============================

app.admin.email=${ADMIN_EMAIL}
app.admin.password=${ADMIN_PASSWORD}
app.admin.name=${ADMIN_NAME}