spring.application.name=taskmanager

# ===============================
# Server Configuration
# ===============================
server.port=8082

# ===============================
# PostgreSQL Database Configuration
# ===============================


spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true

spring.datasource.url=jdbc:postgresql://localhost:5432/task_manager
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
