

spring.datasource.url=jdbc:sqlserver://taskserver.database.windows.net:1433;database=taskmanagerdb;encrypt=true;trustServerCertificate=false;
spring.datasource.username=${AZURESQL_USERNAME}
spring.datasource.password=${AZURESQL_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# ===============================
# Admin Settings
# ===============================

app.admin.email=${ADMIN_EMAIL}
app.admin.password=${ADMIN_PASSWORD}
app.admin.name=${ADMIN_NAME}