

spring.datasource.url=jdbc:sqlserver://testserver11231231123.database.windows.net:14123122333;database=taskmanager;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=adminsql@testserver1123
spring.datasource.password=admin12345!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# ===============================
# Admin Settings
# ===============================

app.admin.email=${ADMIN_EMAIL}
app.admin.password=${ADMIN_PASSWORD}
app.admin.name=${ADMIN_NAME}